apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-hdfs 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-hdfs 
    spec:
      containers:
      - name: web-hdfs 
        image: besn0847/x86-hdfs
        ports:
          - containerPort: 26412
---
apiVersion: v1
kind: Service
metadata:
  name: svc-hdfs
  labels:
    run : web-hdfs 
  namespace: default
spec:
  ports:
  - nodePort: 32412
    port: 26412
    protocol: TCP
    targetPort: 26412
  selector:
    app: web-hdfs 
  type: NodePort
